/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.htoyama.test.simplethrift.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-31")
public enum State implements org.apache.thrift.TEnum {
  Value1(1),
  Value2(2),
  Value3(3);

  private final int value;

  private State(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static State findByValue(int value) { 
    switch (value) {
      case 1:
        return Value1;
      case 2:
        return Value2;
      case 3:
        return Value3;
      default:
        return null;
    }
  }
}
